# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @   ____   _____  _____  _    _   _  _    _____   @
# @  |  _ \ | ____||  ___|/ \  | | | || |  |_   _|  @
# @  | | | ||  _|  | |_  / _ \ | | | || |    | |    @
# @  | |_| || |___ |  _|/ ___ \| |_| || |___ | |    @
# @  |____/ |_____||_| /_/   \_\\___/ |_____||_|    @
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thank_you_matcher
    username: thank-you-matcher-service
    password: ${POSTGRES_PASSWORD_FILE:thank_you_matcher_password}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @   ____   _____ __     __  @
# @  |  _ \ | ____|\ \   / /  @
# @  | | | ||  _|   \ \ / /   @
# @  | |_| || |___   \ V /    @
# @  |____/ |_____|   \_/     @
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
