# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @   ____   _____  _____  _    _   _  _    _____   @
# @  |  _ \ | ____||  ___|/ \  | | | || |  |_   _|  @
# @  | | | ||  _|  | |_  / _ \ | | | || |    | |    @
# @  | |_| || |___ |  _|/ ___ \| |_| || |___ | |    @
# @  |____/ |_____||_| /_/   \_\\___/ |_____||_|    @
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${GOOGLE_CLIENT_ID:client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


---
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @   ____   _____ __     __  @
# @  |  _ \ | ____|\ \   / /  @
# @  | | | ||  _|   \ \ / /   @
# @  | |_| || |___   \ V /    @
# @  |____/ |_____|   \_/     @
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
spring:
  config:
    activate:
      on-profile: dev

---
# @@@@@@@@@@@@@@@@@@@@@@
# @    ___      _      @
# @   / _ \    / \     @
# @  | | | |  / _ \    @
# @  | |_| | / ___ \   @
# @   \__\_\/_/   \_\  @
# @@@@@@@@@@@@@@@@@@@@@@
spring:
  config:
    activate:
      on-profile: qa

---
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @   ____   ____    ___   ____    @
# @  |  _ \ |  _ \  / _ \ |  _ \   @
# @  | |_) || |_) || | | || | | |  @
# @  |  __/ |  _ < | |_| || |_| |  @
# @  |_|    |_| \_\ \___/ |____/   @
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
spring:
  config:
    activate:
      on-profile: prod